### ISSUE TITLE
why disabling interrupts during context switching ?

### ISSUE THREAD

**Issue by 0x0laurent** [the-grue/rmtx#1]
why disabling interrupts during context switching ?

_tswitch:
SAVE:	
        cli
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	pushf
	mov  bx,_running
	mov  2[bx],sp

FIND:	call _scheduler

RESUME:
	mov  bx,_running
	mov  sp,2[bx]
	popf
	pop  di
	pop  si
	pop  bp
	pop  dx
	pop  cx
	pop  bx
	pop  ax

        sti
	ret

**Comment by the-grue** [comment]
Hi @0x0laurent this code is from the book "Design and Implementation of the MTX Operating System" by K. C. Wang.  I would recommend consulting the book as it may explain the reason why the author chose to do this.

**Comment by 0x0laurent** [comment]
Hi @the-grue actualy i read the book and the author didn't mention the reason for disabling interrupts during context switching. I'm looking for people that worked with MTX to help.
